### PR TITLE
dart pub upgrade --major-versions

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Review by johnpryan — APPROVED** [review]

**Review by parlough — APPROVED** [review]
Thanks for updating and upgrading codemirror :)

**Comment by domesticmouse** [comment]
Please let me know when this is in prod. We are effectively soak testing the null safe version of https://github.com/google/codemirror.dart and once we are happy with it I'll bump CodeMirror's null safety to full release.

thanks!

**Comment by johnpryan** [comment]
@domesticmouse deployed!

**Comment by domesticmouse** [comment]
thanks!

**Pull request merged**
