### PR TITLE
Polymer 1.0 -> 2.0 initial migration

### PR DESCRIPTION
**Pull request by domesticmouse**
This is my initial attempt at moving dart-pad from Polymer 1.0 to Polymer 2.0. 

Feedback greatly appreciated!

### CODE REVIEW

**Comment by domesticmouse** [comment]
Now that I've looked more closely at the running instance, instead of the source base, I'm starting to wonder just how much of this is actually used, and where. I'm starting to think I can re-implement most of the current flex-box interface in AngularDart fairly easily.

Which I'm guessing means I've completely missed something obvious. Please feel free to enlighten me. Thanks!

**Comment by devoncarew** [comment]
Hi @domesticmouse, thanks for the PR! @jcollins-g is best set up to evaluate it.

> I'm starting to wonder just how much of this is actually used, and where

DartPad essentially has two separate UIs. The main one, which powers dartpad.dartlang.org. It's optimized for a desktop browser, but has a little bit of responsive css in order to render on mobile devices. This UI is written in straight dart:html.

The 2nd UI is for the embedded use case. It's what you see embedded in pages like https://www.dartlang.org/tutorials/language/futures. That UI is written in JS polymer, with some dart:js wrappers to expose some of the controls to Dart. We eventually want to remove the use of Polymer from the site, in order to reduce the maintenance burden. That would _likely_ take the form of:

- removing the embedding UI
- adding a new re-swizzling of the desktop UI, that's has something like a table of contents style navigation over Dart language features, with each leaf node in the TOC being a small dart snippet you can run and play with.

**Comment by jcollins-g** [comment]
This is going to take a bit to review, but I'm excited to do it!  Our tie to Polymer 1 is part of our technical debt.

When using grind serve to try out the new version locally, you can load the embedding demo HTML files to get a sense of how these are used.

**Comment by jcollins-g** [comment]
I'm probably not going to be able to take a detailed look at this until early next week, but will keep you in the queue.  I'm not going to want to land something this complicated until 2.1 is out the door, in any event.  Thanks again for doing this!

**Comment by domesticmouse** [comment]
The main time constraint on this PR is that I understand that Polymer 1.0 will stop working with Chrome 73 in Q1. 

At this point I am exploring how I can help with moving DartPad forward, so please feel free to expand out tasks that you see I could get started on with working down the technical debt.

Thanks!

**Comment by domesticmouse** [comment]
I suspect this PR is a bust. In attempting to test the polymer code paths I tried requesting the following path from my local dev server: http://localhost:8000/embed-inline.html?id=477fb799d21401f46f8c04462fd249c4&horizontalRatio=99&verticalRatio=73

I'd be interested in re-swizzling the embedding UI in straight dart:html but I'm having issues trying to pull polymer out of the codebase. Hints and suggestions gladly accepted.

**Comment by jcollins-g** [comment]
https://www.polymer-project.org/blog/2018-10-02-webcomponents-v0-deprecations indicates that all that is necessary for Polymer 1.x to work on Chrome 73+ is for it to load the polyfills with a script tag.  Our embed.htmls already contain this support.  So while this is a nice to have, it isn't strictly necessary for Q1.

**Comment by domesticmouse** [comment]
Cool, closing this PR out.

**Pull request closed without merging**
