### PR TITLE
Modified visibility

### PR DESCRIPTION
**Pull request by Georgehe4**
Tabs no longer auto switch to html or console on run.
Visibility elements modified instead of display in order to make sure no issues with iframe.
@devoncarew

### CODE REVIEW

**Comment by devoncarew** [comment]
It looks like there are some layout issues with samples like solar and sunflower:

screen shot 2015-06-10 at 9 02 13 pm

Some quick experimentation in devtools didn't turn up any answers...

**Comment by Georgehe4** [comment]
@devoncarew 
Fixed it. Broke it trying to fix css.

**Comment by devoncarew** [comment]
lgtm!

**Comment by Georgehe4** [comment]
Merging

**Pull request merged**
