### PR TITLE
triggers completion on  dot

### PR DESCRIPTION
**Pull request by kasperpeulen**
solves: https://github.com/dart-lang/dart-pad/issues/143

screenshot:

### CODE REVIEW

**Comment by devoncarew** [comment]
+1!

This will the code completion feature to everyone's attention. We have a bit more work - at least on the backend - that we'd like to do. @lukechurch, let's land this when you're comfortable with it being on be default.

**Comment by lukechurch** [comment]
Yup. Sounds good. Great to have this ready when the services are.

**Comment by kaendfinger** [comment]
This is absolutely amazing! :)

**Comment by lukechurch** [comment]
@devoncarew As discussed lets put experimental flags in, and then bring this in backed by the flag. I'll see if I can get to this early in the week.

**Comment by kasperpeulen** [comment]
Trying to get completion on `a-zA-Z|\$\.` working, seems to work quite well, if the popup is not flickering

**Comment by devoncarew** [comment]
The developer options PR is out for review: #181.

@kasperpeulen, the git history of this PR includes a lot of other (already merged) changes. Can you rebase this PR against master, or close it and open a new PR? I think the bulk of this change is ~6 lines in `editor_codemirror.dart`.

**Comment by kasperpeulen** [comment]
Yeah, not sure what was going on there, I actually did click rebase on master, and then all those commits came in. Maybe I should not have done that. But I will create a new PR.

**Comment by kasperpeulen** [comment]
see https://github.com/dart-lang/dart-pad/pull/184

**Pull request closed without merging**
