### PR TITLE
Dialog cancel switched to close on share

### PR DESCRIPTION
**Pull request by Georgehe4**
#698 
screen shot 2015-10-16 at 12 53 20 pm

### CODE REVIEW

**Comment by lukechurch** [comment]
Hey @Georgehe4 good to see you again!

LGTM

**Comment by Georgehe4** [comment]
@lukechurch Glad to be able to help

**Comment by Georgehe4** [comment]
Merging

**Comment by devoncarew** [comment]
:+1: 

fixed #698

**Pull request merged**
