### PR TITLE
Temporarily add a route

### PR DESCRIPTION
**Pull request by domesticmouse**
Adding a route to check a theory around serving a redirect if we aren't serving as dartpad.dev.

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @RedBrogdon

**Comment by RedBrogdon** [comment]
Is this something temporary you're working on to debug our various AEF issues, or is this something that would live on in the code for a while? I'm guessing it's not leaking anything you aren't comfortable leaking?

**Comment by domesticmouse** [comment]
This is in relation to canonicalizing all dartpad traffic to dartpad.dev. I believe the correct place to do this is in DartPad's python loader, if it isn't the correct hostname, issue a 304 redirect to the correct URL.

**Review by RedBrogdon — APPROVED** [review]
LGTM, then.

**Pull request merged**
