### PR TITLE
update the favicon

### PR DESCRIPTION
**Pull request by devoncarew**
- fix https://github.com/dart-lang/dart-pad/issues/811#issuecomment-386394253

### CODE REVIEW

**Comment by chalin** [comment]
Great! Can you let me know once this is live? /cc @kwalrath

**Comment by devoncarew** [comment]
Hmm, the front end (this repo) can't build currently, so unless is ~high priority, it'll be a few weeks.

**Comment by chalin** [comment]
It can wait. Thanks for the heads up.

**Comment by anders-sandholm** [comment]
Any chance we can still get this sorted out before the big I/O splash? 
Pretty please.
Everything else has already or is becoming blue'ish.

**Comment by devoncarew** [comment]
> Everything else has already or is becoming blue'ish.

Gotcha; I'll take a look this evening, and update this bug w/ the status then.

**Comment by Georgehe4** [comment]
Dartpad has been updated with the new image assets (might require a browser refresh): https://dartpad.dartlang.org/

**Comment by devoncarew** [comment]
Awesome, thanks @Georgehe4!

**Pull request merged**
