### PR TITLE
Replace haikunator with fluttering_phrases

### PR DESCRIPTION
**Pull request by parlough**
The Dart 2 updated version of `haikunator` hasn't been updated to pub for over two years now and while I know we don't currently use the names for anything besides display, I think they're quite fun to have and a cute little feature of dartpad.

So I went ahead and created a [similar library](https://pub.dev/packages/fluttering_phrases) of my own with a fresh word bank including some "darty"/"fluttery" attributives and nouns.

[I'd love it if you would contribute some fun attributives and nouns as well! I was having trouble coming up with some :D](https://github.com/parlough/fluttering_phrases)

**Benefits:**
- Don't have to host the updated version in this repository
- Simplified grinder configuration/tasks
- Don't have to worry about future migration to null safety
- Get some nice new phrase combinations
- Increased library flexibility

### CODE REVIEW

**Comment by RedBrogdon** [comment]
This looks like a win to me, and I love the idea of removing a third_party dependency. It's a big enough change, though, that I'd like a second opinion.

@devoncarew @domesticmouse @johnpryan, any thoughts here?

**Comment by devoncarew** [comment]
@parlough - can you attach some examples of the names that are generated? I like the names that haikunator could generate, but am not attached to that package specifically, and agree that moving off a non-supported package would be a good idea.

**Comment by devoncarew** [comment]
BTW - thanks for all your contributions! Here, dartdoc - https://github.com/dart-lang/dartdoc/pulls/parlough - and I assume other repos as well :)

**Comment by parlough** [comment]
@devoncarew My pleasure, I enjoy working on these Dart projects, particularly ones which can help others learn =D

As for the titles the package generates, the default is rather similar to haikunator simply with a different bank of attributives and nouns. Using the default arguments, here are 40 example generated titles: https://gist.github.com/parlough/37296a53dd9feed79e1a1221f66f1a73

If desired there are few things which can be optionally configured:
- The delimiter can be changed to a different string or removed.
- The ending token can be removed, changed to a different length, or generated with a different radix.
- A seed can optionally be specified if a caller wants more consistent generation.
- The attributives and nouns used can be overriden and you can use the spread operator to easily include the defaults as well.

**Comment by johnpryan** [comment]
This sounds good to me - `haikunator` is currently Dart 2 incompatible and will likely cause us problems soon.

**Review by domesticmouse — APPROVED** [review]

**Review by RedBrogdon — APPROVED** [review]

**Comment by RedBrogdon** [comment]
It looks like those generated strings are equivalent to the ones we've got now.

@devoncarew, if this looks good to you, it's ready to land.

**Comment by domesticmouse** [comment]
I'm guessing @devoncarew is busy =)

**Comment by devoncarew** [comment]
Sorry - I saw this update but got distracted at the time. lgtm :)

**Comment by domesticmouse** [comment]
Thanks @devoncarew =)

**Pull request merged**
