### PR TITLE
Export wiki added

### PR DESCRIPTION
**Pull request by Georgehe4**
screen shot 2015-07-30 at 4 12 20 pm

#622
Added link to guide on exporting. Links to 
https://github.com/dart-lang/dart-pad/wiki/Exporting-Guide.

### CODE REVIEW

**Comment by Georgehe4** [comment]
@devoncarew @lukechurch

**Comment by devoncarew** [comment]
lgtm

**Comment by lukechurch** [comment]
We'd discussed changing this to 'Open in DartPad'.

Could we make that change before this one?

**Comment by Georgehe4** [comment]
Merging.

**Pull request merged**
