### PR TITLE
remove the clock sample

### PR DESCRIPTION
**Pull request by devoncarew**
Remove the clock sample; fix https://github.com/dart-lang/dart-pad/issues/695.

### CODE REVIEW

**Comment by lukechurch** [comment]
lgtm

**Comment by lukechurch** [comment]
Bouncing broken link icons are only amusing for so long...

**Comment by devoncarew** [comment]
Yeah, looks like time ran out for this sample -

**Comment by kwalrath** [comment]
Ouch, @devoncarew.

**Pull request merged**
