### PR TITLE
Allow popups from the playground and workshop iframes

### PR DESCRIPTION
**Pull request by srawlins**
This is required for the url_launcher plugin.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
I'd enable for workshops, as I'm sure someone will write a plugin workshop sooner or later. 

I'll defer to @johnpryan and @RedBrogdon on embeds.

**Comment by srawlins** [comment]
CC @johnpryan I've made this change to workshop as well.

**Comment by johnpryan** [comment]
Could we also add this to the `embed-*.html` files?

**Comment by srawlins** [comment]
Done!

**Review by johnpryan — APPROVED** [review]
LGTM!

**Pull request merged**
