### PR TITLE
Vulcanization timing

### PR DESCRIPTION
**Pull request by Georgehe4**
Vulcanization.
Timing for load ~1000ms.

### CODE REVIEW

**Comment by Georgehe4** [comment]
Visual bug fixes as well.

**Comment by Georgehe4** [comment]
@devoncarew

**Comment by devoncarew** [comment]
Great! Can you:

- briefly summarize the async / defer `<script>` changes - it'll be good to have that info in this PR if we have to revisit making loading more performant again
- make similar script changes to the two other embeddings (I just see `embed-dart.html` in here)

**Comment by Georgehe4** [comment]
Async/defer:
Async operations for smaller files that do no influence other scripts allow us to request and execute code ASAP. If we vulcanize our code, async does not matter since all code will be immediately executed.

Defer operations for critical files that rely on other components lets us load elements in order without stalling the linear rendering of the page. Defer is applied to embed.dart and codemirror.js because our dart program relies on codemirror assets being loaded in.

**Comment by devoncarew** [comment]
lgtm!

**Comment by Georgehe4** [comment]
Merging. Also not that this PR has a vulcanized time of ~1000ms, while the minimum that we experienced at some point during the process was ~500ms. Unfortunately, we cannot replicate it but should aim to reach it again in the future.

**Comment by Georgehe4** [comment]
Note: Return true change prevents double injection of codemirror. No longer needed due to html file no longer being programmatically injected.

**Pull request merged**
