### PR TITLE
Bower update

### PR DESCRIPTION
**Pull request by jcollins-g**
Updates Polymer to latest 1.x version via "bower update".  Also adjusted the "resolutions" line in bower.json to a version of polymer that actually exists.  Verified that embedded versions of DartPad continue to work properly with some manual smoke testing.

This will close 9 of 12 of the outstanding alerts (#870)

### CODE REVIEW

**Comment by devoncarew** [comment]
Is this hosted somewhere where we could try this out? I normally test this via the `/embeddings_demo.html` page.

**Comment by jcollins-g** [comment]
No.  You should be able to pull the branch and do "grind serve" to run it locally, however.

**Comment by devoncarew** [comment]
Thanks! I did patch it in. It looks like the embedding views have regressed a bit; those may not be related to this change.

From looking at the https://www.dartlang.org/guides/language/language-tour page, it looks like it only uses the 'embed-inline' version (the third one from here: https://dartpad.dartlang.org/embeddings_demo.html). That looks and acts the same before and after this PR.

**Comment by jcollins-g** [comment]
https://jcollins-pr872-dot-dart-pad.appspot.com/ is serving this PR.

**Pull request merged**
