### PR TITLE
Bump Firebase JS SDKs to 8.6.1

### PR DESCRIPTION
**Pull request by srawlins**
Here are the recent changelogs starting at 8.6.1:

https://firebase.google.com/support/release-notes/js#version_861_-_may_12_2021

### CODE REVIEW

**Comment by srawlins** [comment]
CC @puf @RedBrogdon

**Review by domesticmouse — APPROVED** [review]

**Comment by srawlins** [comment]
@RedBrogdon asked which version are the current Flutterfire plugins built to work with, because the warnings in the console referenced 8.6.1. A valid question. I'll look up the docs.

**Comment by Salakar** [comment]
> @RedBrogdon asked which version are the current Flutterfire plugins built to work with, because the warnings in the console referenced 8.6.1. A valid question. I'll look up the docs.

FlutterFire is currently fixed to 8.6.1, but as an FYI there's a FlutterFire PR that's in-progress to switch to the v9 SDK (compat) which has some SDK changes that are still being fixed in the PR, eta for shipping is most likely next week.

If there's an urgent requirement for 8.10.0 then we can look at shipping that within the next day or two (let me know) - otherwise our focus has currently been on upgrading to the next major version.

**Comment by srawlins** [comment]
@Salakar thanks so much for helping out! I only picked 8.10.0 because it's the latest non-v9 release; no other reason. I'll flip this back to 8.6.1, which I see is referenced in the Getting Started docs.

**Pull request merged**
