### PR TITLE
Replace `textTheme.headline4` with `textTheme.headlineMedium`

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Review by parlough — APPROVED** [review]
Looks good to me, but I don't think I have write access so this review might not work.

_Edit: Yeah I don't, sorry!_

**Comment by domesticmouse** [comment]
PTAL @johnpryan

**Review by johnpryan — APPROVED** [review]

**Comment by johnpryan** [comment]
Are there any other Material 2 usages we can see?

**Comment by domesticmouse** [comment]
> Are there any other Material 2 usages we can see?

I believe most of the Flutter samples that can be accessed in DartPad are loaded from GitHub. I have updated all of the gists shared via the shared github account.

**Pull request merged**
