### PR TITLE
removed unused dart:async

### PR DESCRIPTION
**Pull request by Himanshuranjan30**
removed unused dart:async as Future and Streams are already implemented in dart:core as per Dart 2.1.

### CODE REVIEW

**Comment by Himanshuranjan30** [comment]
any updates on this @domesticmouse ?

**Comment by johnpryan** [comment]
`dart:async` isn't technically unused since `Future` is used in the library. For example, both of these programs are considered valid:

```
import 'dart:async';

void main() {
  Future(() {});
}
```

```
void main() {
  Future(() {});
}
```

Here's the SDK issue to follow: https://github.com/dart-lang/sdk/issues/34401

**Comment by Himanshuranjan30** [comment]
> `dart:async` isn't technically unused since `Future` is used in the library. For example, both of these programs are considered valid:
> 
> ```
> import 'dart:async';
> 
> void main() {
>   Future(() {});
> }
> ```
> 
> ```
> void main() {
>   Future(() {});
> }
> ```
> 
> Here's the SDK issue to follow: [dart-lang/sdk#34401](https://github.com/dart-lang/sdk/issues/34401)

Future is already included in dart:core which is an automatically implemented library as per Dart 2.1 @johnpryan

**Comment by johnpryan** [comment]
> Future is already included in dart:core which is an automatically implemented library as per Dart 2.1 @johnpryan

Correct, that's why the analyzer didn't catch this.

**Review by johnpryan — APPROVED** [review]

**Pull request merged**
