### PR TITLE
red button on error

### PR DESCRIPTION
**Pull request by kasperpeulen**
Not totally sure about it, but I thought wouldn't hurt to share the code here.

I do think it looks pretty cool, but maybe a bit visual distracting if it changes color all the time.

and here an better quality png:
image

related issue:https://github.com/dart-lang/dart-pad/issues/187

### CODE REVIEW

**Comment by devoncarew** [comment]
I'm not 100% sure on the aesthetics. I think the thing to take away from https://github.com/dart-lang/dart-pad/issues/187 is that we want better visibility when running the app might not produce the desired results. My 0.02 would probably be an icon badge (an error or warning icon overlaying the bottom, right corner of the button by 50%). This wouldn't change the look of the button; it would tell users that there are issues and hitting run right now probably won't work great.

But this is a lower priority issue - unless you get super motivated we can hold off on implementing it.

**Comment by sethladd** [comment]
Happy to explore different UI options. However, I do want the Run button
itself to indicate what's going to happen (error, warning, should work).
Using a "badge" over the button might work, but I don't seem to recall any
Material Design that overlays info on top of a button.

I do disagree about the priority, though. I'd bump to medium. If we get the
UI right, this is a really nice feedback boost to users.

Devon, if we go with a "badge" instead of changing the button color, can we
use colors?

**Comment by kasperpeulen** [comment]
@devoncarew 
Do you mean with badge something, like on the right ?

image

**Comment by devoncarew** [comment]
By badge, I mean something like this:

screen shot 2015-03-28 at 6 52 30 pm

It's a smaller icon or UI element, centered around a corner, and decorates the meaning of the main element. Like an in-box email count; in this case a warning or error count.

Medium priority sounds fine :) I would like to be happy with the end UI -

**Comment by sethladd** [comment]
I'm not feeling the badge. I feel like badges don't alter the expectations
I get when I click/press the button. Badges are there to give me an idea of
what's behind the function, but the function itself works exactly the same
with or without the badge.

If there's 1 or more errors, the program will not run. The run button
should reflect that.

If my executable is broken, do I even want to run it?

Kasper, I love the third Run button (on the far left). To me, that's very
clear.

**Comment by kasperpeulen** [comment]
I've been trying some badges as you suggested, but I couldn't make them look right. 

I actually think that this looks kind of neat. It's a sublte, but I think it is clear enough:


Or maybe adding colors to the icon:
image

**Comment by sethladd** [comment]
What does the second button mean? (the gray triangle)

Should we turn the first button's arrow green (implying "good to go!")

**Comment by kasperpeulen** [comment]
@sethladd I thought about that as an alternative if you don't want any colors, then both warning and errors would give a grey warning icon.

Here is some more alternatives:

image

**Comment by sethladd** [comment]
I'm a fan of 2, 5 (though, I would make the icon smaller, matching the width of the box in 7), 7

**Comment by sethladd** [comment]
Maybe it's an optical illusion, but it doesn't look like the icons have the same width, in your last screenshot. The green button looks narrower than the square, and the triangle looks wider than the square.

Regardless, I like the green for Good, yellow for Warning, and red for Error.

**Comment by kasperpeulen** [comment]
According to the html the first has width 18px, second 17px and the third 17px. I agree, it doesn't look that way, but it looks fine to me.

Let's see what devoncarew and lukechurch prefer.

**Comment by kasperpeulen** [comment]
see https://github.com/dart-lang/dart-pad/pull/192

**Pull request closed without merging**
