### PR TITLE
Add mobile detection and server redirect

### PR DESCRIPTION
**Pull request by lukechurch**
@devoncarew PTAL @sethladd FYI

I've also pushed to: http://mob.dart-pad.appspot.com/

This should give you the normal UI from desktop, and alternate from phone and tablet. I've tested in synthetic browsers, and on a Nexus 6. If you could give it a spin from any other hardware you have to hand that'd be great.

I've also tested with consuming gists, but if you could test that a little more as well, that'd be appreciated.

### CODE REVIEW

**Comment by lukechurch** [comment]
Addressed #287

**Comment by kasperpeulen** [comment]
works fine at my mobile phone :)

**Comment by lukechurch** [comment]
@googlebot the third party code is going into third party.

**Comment by lukechurch** [comment]
@devoncarew GTG?

**Comment by devoncarew** [comment]
lgtm!

**Pull request merged**
