### PR TITLE
fix: don't bind cmd-1 to quick fixes (#500)

### PR DESCRIPTION
**Pull request by kasperpeulen**

### CODE REVIEW

**Comment by devoncarew** [comment]
Hmm, it does fix the original issue, but I think of `cmd-1` as quick fix. People who are used to that keybinding would be switching tabs when they wanted to show quick fixes...

**Comment by kasperpeulen** [comment]
hmm, right, difficult

**Comment by kevmoo** [comment]
@devoncarew I'd argue that web apps should avoid taking over expected browser behavior

... I hit the cmd-1 issue almost every time I use dartpad.

**Comment by devoncarew** [comment]
We ran into this exact same issue with Atom. Some group of developers expect quick-fix on cmd-1, some expect to switch tabs with it. There's not clear solution here -

I'll merge and we can see how that works for people -

Thanks for the PR @kasperpeulen!

**Comment by kevmoo** [comment]
Thanks. For browser apps, I think this is the best call.

**Pull request merged**
