### PR TITLE
updates and fixes

### PR DESCRIPTION
**Pull request by devoncarew**
- fixed an issue where error toasts would disappear
- fixed display issues with compilation progress in the embedded views
- fixed z-order issues with the error display in the embedded and mobile views
- updates for regressions in consuming the latest polymer version
- make the build faster
- make the layout and padding for the embedded views consistent
- improve the dartdoc panel fonts and styles
- improve caching of requested resources for the desktop version

### CODE REVIEW

**Comment by devoncarew** [comment]
screen shot 2015-10-10 at 2 24 11 pm

screen shot 2015-10-10 at 2 25 42 pm

**Comment by devoncarew** [comment]
Currently served from dev.dart-pad.appspot.com.

**Comment by lukechurch** [comment]
lgtm

Could you briefly describe the changes to the caching, or where the code that adjusts those is?

**Comment by devoncarew** [comment]
The svg images in the desktop version were always being requested - more or less everything else was being cached. I changed the references (here: https://github.com/dart-lang/dart-pad/pull/699/files#diff-891cb8b0eccdee8d6021d9b25f8119eeR517) to a dir that was marked as cached, and added the referenced svgs into that dir.

**Comment by devoncarew** [comment]
You can see the caching issue if you open the prod desktop version w/ devtools.

**Pull request merged**
