### PR TITLE
proposed: make run button blue

### PR DESCRIPTION
**Pull request by johnpryan**
This will help the editor match `dart.dev` and `flutter.dev`

F568B657-B05D-4F4D-9DBA-8F945D1355EE-90654-000037D44DC2524A

### CODE REVIEW

**Comment by domesticmouse** [comment]
Please run this past UX, having the go button be green is idiomatic given traffic lights and the like. (Except in Japan, where they are a greenish hue of blue, because history)

**Comment by RedBrogdon** [comment]
Paging @galeyang...

**Comment by galeyang** [comment]
I talked to @InMatrix about this. We think it's good to keep it green as both IDEs we support (Android Studio / IntelliJ) use a green button.

image
image

**Comment by johnpryan** [comment]
👍 no problem!

**Pull request closed without merging**
