### PR TITLE
Add Pub package versions to the VersionResponse proto; UI elements

### PR DESCRIPTION
**Pull request by srawlins**
Deploy with https://github.com/dart-lang/dart-services/pull/704.

This change adds the package versions to the VersionResponse and also a dialog which displays them.

Without considering new UI, the dialog trigger is "hidden"; you click on the current version numbers in the bottom right. I think the Material "info" icon would be good; either to the right or the left of the version numbers in the bottom right.

Each package name and version link to pub.dev in a new tab.

### CODE REVIEW

**Review by johnpryan — COMMENTED** [review]
LGTM - could we hold off on this and https://github.com/dart-lang/dart-services/pull/704 until after next week?

**Review by johnpryan — APPROVED** [review]

**Comment by srawlins** [comment]
Sounds good to me.

**Review by domesticmouse — APPROVED** [review]

**Comment by srawlins** [comment]
CI looks good so far...

**Comment by johnpryan** [comment]
cancelling the dev channel run

**Comment by domesticmouse** [comment]
Are you deploying this to prod? The [backend PR](https://github.com/dart-lang/dart-services/pull/704) is currently conflicted.

**Pull request merged**
