### PR TITLE
Update to new theme to improve accessibility

### LINKED ISSUE #1628: Improve dark mode contrast
Not sure when but DartPad now seems to only allow dark mode, whereas before it had light mode.

This is making using DartPad very difficult as it is very difficult to see the code against a black background.

Bring back light mode or a least an option to change display themes.

### PR DESCRIPTION
**Pull request by johnpryan**
This applies the new theme with higher contrast.

Staging links:
- https://20210615t194421-dot-dart-pad.appspot.com/
- https://20210615t194421-dot-dart-pad.appspot.com/embed-flutter.html
- https://20210615t194421-dot-dart-pad.appspot.com/embed-flutter.html?theme=dark
- https://20210615t194421-dot-dart-pad.appspot.com/workshops.html?webserver=/example/workshops/dart

fixes #1628

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Minor oddity which seems unrelated to this PR:

Screen Shot 2021-06-16 at 4 05 18 pm

**Comment by mit-mit** [comment]
I like it! My only style comment is that I find the greenish hue of the annotations color (used for line numbers and the Console and Documentation labels) a bit of a mismatch. I tried changing it to use `gray` like before, and I like that a lot better:

3DNKwYtKYXyLtyc

**Review by srawlins — APPROVED** [review]
Oooh excellent!

**Comment by johnpryan** [comment]
@domesticmouse I think the text issue is https://github.com/dart-lang/dart-pad/issues/1855.

**Comment by mit-mit** [comment]
🎆

**Pull request merged**
