### PR TITLE
Fixed quantifier errors, packing wording errors

### PR DESCRIPTION
**Pull request by Georgehe4**
Quantifiers now correctly categorize, bins also changed slightly.
Wording for package imports modified.

### CODE REVIEW

**Comment by Georgehe4** [comment]
@devoncarew

**Comment by devoncarew** [comment]
lgtm

Can you reference the bug numbers that this PR addresses? Thanks!

**Comment by Georgehe4** [comment]
#468 
#469 
#470
#471 
#472

**Comment by devoncarew** [comment]
Great, thanks! lgtm - I'll re-deploy to dev as soon as this is merged.

**Comment by Georgehe4** [comment]
Merging.

**Pull request merged**
