### PR TITLE
Implicit casts false

### PR DESCRIPTION
**Pull request by domesticmouse**
Initial attempt at using `implicit-casts: false`. However, I am seeing the following error at run time after this patch. Hints on how to debug?

```
playground.dart.js:458 Uncaught TypeError: Instance of 'minified:R': type 'minified:R' is not a subtype of type 'minified:q<String, dynamic>'
    at Object.c (playground.dart.js:458)
    at Object.l (playground.dart.js:811)
    at kV.$2 (playground.dart.js:12369)
    at Object.zX (playground.dart.js:413)
    at Object.w4 (playground.dart.js:2244)
    at rL (playground.dart.js:3079)
    at playground.dart.js:12365
    at (index):18576
```

### CODE REVIEW

**Comment by RedBrogdon** [comment]
If you haven't already, try running via `webdev` rather than `grind serve`. That should use dartdevc rather than dart2js, which will give you proper sourcemaps and the ability to see which line of actual Dart is failing.

**Comment by domesticmouse** [comment]
Nice, `webdev serve` clued me in to the problem. PTAL =)

**Comment by domesticmouse** [comment]
PTAL @RedBrogdon 😁

**Comment by kevmoo** [comment]
@domesticmouse – related to https://github.com/dart-lang/sdk/issues/40296 perhaps?

**Comment by domesticmouse** [comment]
@kevmoo I’m unsure what you are getting at. All of this work is being done on dart stable. The error I had was due to asserting an incorrect type at the dart/JavaScript boundary. With that assertion gone, the generated code is fine.

**Pull request merged**
