### PR TITLE
Add missing favicons and include other sizes

### PR DESCRIPTION
**Pull request by parlough**
The embeds can be opened standalone, but they've been missing a favicon due to the shortcut link pointing to an old version that is no longer present in the directory.

I've also gone ahead and added some other common sizes of the favicon so browsers can use their preferred version.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Which platforms can take advantage of 192x192 over 64x64 pngs for the shortcut icon?

**Comment by parlough** [comment]
I think most(if not all?) modern browsers support 192x192, but I suppose the larger benefit would be if a user downloaded the site as a PWA as they have larger icons. The 64px version was deleted in https://github.com/dart-lang/dart-pad/pull/1204 so perhaps @RedBrogdon may have more context about that.

**Comment by domesticmouse** [comment]
Thanks @parlough, I'll leave it to @RedBrogdon and @johnpryan =)

**Review by johnpryan — COMMENTED** [review]
I think the best-practice is to include different sizes. The browser will only load the appropriate size. I think it might be better to include a 32x32, 192x192, and maybe a few others.

- [Are all favicon sizes fetched from the server?](https://stackoverflow.com/a/8801211/5859156)
- [The 2020 Guide to FavIcons for Nearly Everyone and Every Browser](https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/)

**Comment by parlough** [comment]
> I think the best-practice is to include different sizes. The browser will only load the appropriate size. I think it might be better to include a 32x32, 192x192, and maybe a few others.
> 
> * [Are all favicon sizes fetched from the server?](https://stackoverflow.com/a/8801211/5859156)
> * [The 2020 Guide to FavIcons for Nearly Everyone and Every Browser](https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/)

Good point, I've gone ahead and added `32x32` and `64x64` on top of the `192x192` to all pages.

**Review by johnpryan — APPROVED** [review]

**Pull request merged**
