### PR TITLE
Merge the codelabs branch into main branch

### PR DESCRIPTION
**Pull request by johnpryan**

### CODE REVIEW

**Comment by johnpryan** [comment]
FYI the only unreviewed commit is 4a90fa3, which runs `dart format`.

**Comment by johnpryan** [comment]
@kevmoo should I commit the `.g.dart` files here? The build for b7a9f5b failed because I committed a `.g.dart` file:

```
  [SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. The outputs are: lib/codelabs/src/meta.g.dart
```

But 3353d19 fails because it does analysis before building the project. What's the best-practice here?

**Comment by kevmoo** [comment]
Should have `--delete-conflicting-outputs` in there.

**Comment by johnpryan** [comment]
TBR: @domesticmouse @RedBrogdon

**Review by domesticmouse — COMMENTED** [review]
Trailing LGTM

**Pull request merged**
