### PR TITLE
Embed functionality

### PR DESCRIPTION
**Pull request by Georgehe4**
All 3 embed views now have functionality.
Still need to fix up style and export button.

### CODE REVIEW

**Comment by Georgehe4** [comment]
@devoncarew @lukechurch

**Comment by devoncarew** [comment]
> All 3 embed views now have functionality.

woot! Can you have the export button display an 'under construction' dialog?

lgtm

**Comment by Georgehe4** [comment]
@devoncarew 
Added!
We still have some issues with styling.
I have fixed an issues with the location of the error toasts - though we need to decide where to place the errors.

**Comment by Georgehe4** [comment]
Merging

**Pull request merged**
