### PR TITLE
Add cookie banner

### PR DESCRIPTION
**Pull request by mit-mit**
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Comment by mit-mit** [comment]
Screenshot 2024-11-25 at 15 44 07

**Comment by johnpryan** [comment]
I tested this locally and deployed this to https://sketch-pad-1cebb--cookie-banner-bvpssvbh.web.app, but I'm not seeing the cookie banner. 

cc/ @devoncarew

**Comment by devoncarew** [comment]
> cc/ @devoncarew I remember you mentioning there were some technical issues you noticed when you tried to add this feature?

I was not able to see the banner when I tried this myself, a few months ago. If I remember correctly, I think that the flutter content was always full screen - the banner didn't have any height, or was obscured?

Perhaps I was missing something, or the banner has some other check that wasn't triggering. From the screenshot @mit-mit was able to get it working.

**Comment by johnpryan** [comment]
I think this is because I am in the US.

> The Cookie Notification Bar will only be shown if the user is visiting from an eligible region, so will not be visible if testing from elsewhere (eg. United States).

**Review by johnpryan — APPROVED** [review]

**Comment by mit-mit** [comment]
@johnpryan can you try to test with that and confirm that its working on your end on your staged site? If so, please go ahead and merge.

**Comment by johnpryan** [comment]
LGTM

**Pull request merged**
